# Generated by Django 5.2.1 on 2025-08-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='duracao',
            field=models.IntegerField(help_text='Duração em anos'),
        ),
    ]
